### ISSUE TITLE
Question about populate children

### ISSUE THREAD

**Issue by casalot** [devinivy/bedwetter#25]
I have entities `events` and `eventlinks`. An `event` can have multiple `eventlinks`. And, `eventlinks` are tied to `linktypes`. `populate: true` is set on all `GET` routes.

Defined in the models as:
`events.js`
```javascript
    eventlinks: {
      collection: 'eventlink',
      via: 'event'
    }
```
and
`eventlinks.js`
```javascript
    event: {
      columnName: 'eventId',
      model : 'event'
    },
    linkType: {
      columnName: 'linkTypeId',
      model: 'linktype',
      populate: true
    },
```

When i call the endpoint `/api/eventlinks/1`, I get the details of the `linktype` in the response payload:
```json
{
  "event": {
    "eventDateTime": "2016-07-09T17:21:52.000Z",
    "id": 1,
    "eventType": 1,
    "organisation": 1,
  },
  "linkType": {
    "title": "customer",
    "createdAt": null,
    "updatedAt": null,
    "id": 1,
    "brand": 1
  },
  "createdAt": "2016-07-09T17:31:25.000Z",
  "updatedAt": "2016-07-09T17:31:25.000Z",
  "id": 1,
}
```
But, when I call the endpoint `/api/events/1`, which will include all the `eventlinks`, it only shows the id for the `linkType`:
```
{
  "eventlinks": [
    {
      "createdAt": "2016-07-09T17:31:25.000Z",
      "updatedAt": "2016-07-09T17:31:25.000Z",
      "id": 1,
      "event": 1,
      "linkType": 1
    },
    {
      "createdAt": "2016-07-09T17:31:43.000Z",
      "updatedAt": "2016-07-09T17:31:43.000Z",
      "id": 2,
      "event": 1,
      "linkType": 2
    },
    {
      "createdAt": "2016-07-09T17:32:06.000Z",
      "updatedAt": "2016-07-09T17:32:06.000Z",
      "id": 3,
      "event": 1,
      "linkType": 5
    },
    {
      "createdAt": "2016-07-09T17:32:17.000Z",
      "updatedAt": "2016-07-09T17:32:17.000Z",
      "id": 4,
      "event": 1,
      "linkType": 6
    }
  ],
  "eventType": {
    "title": "customer call",
    "createdAt": null,
    "updatedAt": null,
    "id": 1
  },
  "createdAt": "2016-07-09T17:21:52.000Z",
  "updatedAt": "2016-07-09T17:21:52.000Z",
  "id": 1
}
```

Is this by design?

**Comment by casalot** [comment]
Upon further investigation, it seems this is a waterline specific issue. At present waterline does not provide nested populates.

The only way I could overcome this, is by making a subsequent call to get the "detailed" responses for the child entities:

1. `/api/events/1`   <-- get response for parent
2. `/api/eventlinks?event=1`   <-- get detailed response for child entities

@devinivy, am I on the right track here? Is there any other way currently to do this?

**Comment by devinivy** [comment]
You might want to look into turning `eventlinks` into a through-table using waterline.  If `eventlinks` doesn't contain any information aside from the event id and linktype id, then you should instead create a many-to-many relationship between `events` and `linktypes` and let waterline manage the through-table. Barring that, you can also use hapi's bassmaster plugin to make those two requests at once.

**Comment by casalot** [comment]
Thanks, @devinivy. Yeah, for this data model the many-to-many won't work. I have actually considered bassmaster. Will check it out.

Is there a way to access another model, from within a model's attribute methods? E.g using the waterline `find` on another model?

**Comment by devinivy** [comment]
Ah, no there isn't a way to `find()` an a model instance's attribute.  You might consider writing a special handler for this case rather than using bedwetter.  Or again, turning `eventlinks` into a through-collection [like so](https://github.com/balderdashy/waterline/issues/705#issuecomment-60945411).

**Comment by casalot** [comment]
@devinivy, hopefully this is the last question ... I'm now using bassmaster to get this done.

Here's my route definition:
```javascript
  {
    method: 'GET',
    path: `${process.env.ENDPOINT_PREFIX_API_CSQA}/assessments/{id}/batch`,
    config: {
      handler: function(request, reply) {
        request.server.inject({
          method: 'POST',
          url: '/batch',
          payload: '{"requests": [{"method":"GET","path":"/api/csqa/assessments/' + request.params.id + '"},{"method":"GET","path":"/api/csqa/assessmenttimeline/$0.currentState.id"}]}'
        },function (res) {
          if (res) {
            let batch = res.result;
            reply(batch);
          }
        });
      },
      auth: false
    }
  }
```

And, the model:
```javascript
'user strict';

module.exports = {
  identity: 'assessment',
  connection: 'dbCSQA',
  tableName: 'Assessment',
  migrate: 'safe',
  autoPK: false,
  autoCreatedAt: 'createdAt',
  autoUpdatedAt: 'updatedAt',
  attributes: {
    id: {
      columnName: 'assessmentId',
      type: 'integer',
      primaryKey: true,
      autoIncrement: true,
      unique: true
    },
    event: {
      columnName: 'eventId',
      model: 'event'
    },
    assessmentDateTime: {
      type : 'datetime',
      required : true
    },
    agent: {
      columnName: 'userId',
      model: 'user'
    },
    questionnaire: {
      columnName: 'questionnaireId',
      model: 'questionnaire'
    },
    timeline: {
      collection: 'assessmenttimeline',
      via: 'assessment'
    },
    assessmentAnswers: {
      collection: 'assessmentanswer',
      via: 'assessment'
    },
    getCurrentState: function() {
      if (this.timeline.length) {
        let currentState = {};
        currentState.id = this.timeline[this.timeline.length - 1].id;
        currentState.assignedToUser = this.timeline[this.timeline.length - 1].assignedToUser;
        currentState.assessmentStatus = this.timeline[this.timeline.length - 1].assessmentStatus;
        return currentState;
      }
    },
    toJSON: function() {
      var obj = this.toObject();
      obj.currentState = this.getCurrentState().id;
      return obj;
    }
  }
}
```

When call the `/api/csqa/assessments/1/batch` request, if throws a 500.

When replacing the `$0.currentState.id` with a hardcoded id value, e.g. `/api/csqa/assessmenttimeline/8`, or if I use another model attribute, e.g. `/api/csqa/assessmenttimeline/$0.id`, it works.

Is this because the `currentState` attributed is derived via a model method?

**Comment by casalot** [comment]
Nevermind. I've realized that using the `toObject()` will sort this out:

```javascript
    toObject: function() {
      var obj = this;
      obj.currentState = this.getCurrentState();
      return obj;
    }
```

**Comment by devinivy** [comment]
Excellent!  Just make sure `toObject()` does return a POJO.  Closing, but we can reopen if necessary.
